# Generated by Django 2.0.5 on 2018-05-07 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180507_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleepsetting',
            name='from_hour',
            field=models.TimeField(default=datetime.datetime(2018, 5, 7, 10, 41, 29, 597178)),
        ),
        migrations.AlterField(
            model_name='sleepsetting',
            name='to_hour',
            field=models.TimeField(default=None),
        ),
    ]
