# Generated by Django 2.0.5 on 2018-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180507_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepsetting',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='sleepsetting',
            name='to_hour',
        ),
        migrations.AddField(
            model_name='sleepsetting',
            name='from_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='sleepsetting',
            name='to_time',
            field=models.TimeField(default='06:00'),
        ),
    ]
